"""baseline_schema_v124_31_tables

Baseline migration: 31 active tables from TT-RSS schema version 124
+ 75 seed rows across 6 lookup tables (FK insertion order).

Source: ttrss/schema/ttrss_schema_pgsql.sql (entire file, version 124)
New: no PHP equivalent — Alembic replaces ttrss/classes/dbupdater.php:DbUpdater
     (PHP ran raw SQL version files; Alembic generates from ORM metadata).

Seed data sources (ttrss_schema_pgsql.sql INSERT statements):
  ttrss_prefs_types   (lines 282-284)  — 3 rows, FK parent of ttrss_prefs.type_id
  ttrss_prefs_sections (lines 290-293) — 4 rows, FK parent of ttrss_prefs.section_id
  ttrss_filter_types  (lines 192-198)  — 7 rows
  ttrss_filter_actions (lines 208-229) — 8 rows
  ttrss_prefs         (lines 302-352)  — 52 rows + access_level UPDATE (lines 354-362)
  ttrss_version       (line 264)       — 1 row (schema_version=124)
  Total: 75 seed rows.

Revision ID: 35c0c917fdec
Revises:
Create Date: 2026-04-04 02:06:24.092355
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '35c0c917fdec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ttrss_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=250), nullable=False),
    sa.Column('cached_content', sa.Text(), nullable=True),
    sa.Column('no_orig_date', sa.Boolean(), nullable=False),
    sa.Column('date_entered', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=250), nullable=False),
    sa.Column('plugin_data', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('author', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_ttrss_entries_date_entered'), 'ttrss_entries', ['date_entered'], unique=False)
    op.create_index(op.f('ix_ttrss_entries_updated'), 'ttrss_entries', ['updated'], unique=False)
    op.create_table('ttrss_feedbrowser_cache',
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('feed_url')
    )
    op.create_table('ttrss_filter_actions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ttrss_filter_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ttrss_linked_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=False),
    sa.Column('last_status_in', sa.Integer(), nullable=False),
    sa.Column('last_status_out', sa.Integer(), nullable=False),
    sa.Column('access_key', sa.String(length=250), nullable=False),
    sa.Column('access_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key')
    )
    op.create_table('ttrss_prefs_sections',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_prefs_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_sessions',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expire', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ttrss_sessions_expire_index', 'ttrss_sessions', ['expire'], unique=False)
    op.create_table('ttrss_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('pwd_hash', sa.String(length=250), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('email_digest', sa.Boolean(), nullable=False),
    sa.Column('last_digest_sent', sa.DateTime(), nullable=True),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('twitter_oauth', sa.Text(), nullable=True),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('resetpass_token', sa.String(length=250), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('ttrss_version',
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('schema_version')
    )
    op.create_table('ttrss_access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key', sa.String(length=250), nullable=False),
    sa.Column('feed_id', sa.String(length=250), nullable=False),
    sa.Column('is_cat', sa.Boolean(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_archived_feeds',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('site_url', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_cat_counters_cache',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'owner_uid')
    )
    op.create_index('ttrss_cat_counters_cache_owner_uid_idx', 'ttrss_cat_counters_cache', ['owner_uid'], unique=False)
    op.create_table('ttrss_counters_cache',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'owner_uid')
    )
    op.create_index('ttrss_counters_cache_feed_id_idx', 'ttrss_counters_cache', ['feed_id'], unique=False)
    op.create_index('ttrss_counters_cache_owner_uid_idx', 'ttrss_counters_cache', ['owner_uid'], unique=False)
    op.create_index('ttrss_counters_cache_value_idx', 'ttrss_counters_cache', ['value'], unique=False)
    op.create_table('ttrss_enclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=250), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['ttrss_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttrss_enclosures_post_id'), 'ttrss_enclosures', ['post_id'], unique=False)
    op.create_table('ttrss_entry_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('date_entered', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_id'], ['ttrss_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ttrss_entry_comments_ref_id_index', 'ttrss_entry_comments', ['ref_id'], unique=False)
    op.create_table('ttrss_error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=True),
    sa.Column('errno', sa.Integer(), nullable=False),
    sa.Column('errstr', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('lineno', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_feed_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('view_settings', sa.String(length=250), nullable=False),
    sa.Column('parent_cat', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_cat'], ['ttrss_feed_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_filters2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('match_any_rule', sa.Boolean(), nullable=False),
    sa.Column('inverse', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_labels2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('fg_color', sa.String(length=15), nullable=False),
    sa.Column('bg_color', sa.String(length=15), nullable=False),
    sa.Column('caption', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_linked_feeds',
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['ttrss_linked_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_url', 'instance_id')
    )
    op.create_table('ttrss_plugin_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_prefs',
    sa.Column('pref_name', sa.String(length=250), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('def_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['ttrss_prefs_sections.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ttrss_prefs_types.id'], ),
    sa.PrimaryKeyConstraint('pref_name')
    )
    op.create_index('ttrss_prefs_pref_name_idx', 'ttrss_prefs', ['pref_name'], unique=False)
    op.create_table('ttrss_settings_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=250), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.Column('purge_interval', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('favicon_avg_color', sa.String(length=11), nullable=True),
    sa.Column('site_url', sa.String(length=250), nullable=False),
    sa.Column('auth_login', sa.String(length=250), nullable=False),
    sa.Column('parent_feed', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('auth_pass', sa.String(length=250), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('include_in_digest', sa.Boolean(), nullable=False),
    sa.Column('rtl_content', sa.Boolean(), nullable=False),
    sa.Column('cache_images', sa.Boolean(), nullable=False),
    sa.Column('hide_images', sa.Boolean(), nullable=False),
    sa.Column('cache_content', sa.Boolean(), nullable=False),
    sa.Column('last_viewed', sa.DateTime(), nullable=True),
    sa.Column('last_update_started', sa.DateTime(), nullable=True),
    sa.Column('update_method', sa.Integer(), nullable=False),
    sa.Column('always_display_enclosures', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('mark_unread_on_update', sa.Boolean(), nullable=False),
    sa.Column('update_on_checksum_change', sa.Boolean(), nullable=False),
    sa.Column('strip_images', sa.Boolean(), nullable=False),
    sa.Column('view_settings', sa.String(length=250), nullable=False),
    sa.Column('pubsub_state', sa.Integer(), nullable=False),
    sa.Column('favicon_last_checked', sa.DateTime(), nullable=True),
    sa.Column('auth_pass_encrypted', sa.Boolean(), nullable=False),
    sa.Column('last_etag', sa.String(length=250), nullable=True),
    sa.Column('last_modified', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['ttrss_feed_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_feed'], ['ttrss_feeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttrss_feeds_cat_id'), 'ttrss_feeds', ['cat_id'], unique=False)
    op.create_index(op.f('ix_ttrss_feeds_owner_uid'), 'ttrss_feeds', ['owner_uid'], unique=False)
    op.create_table('ttrss_filters2_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('action_param', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ttrss_filter_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['ttrss_filters2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_user_labels2',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['ttrss_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['ttrss_labels2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('label_id', 'article_id')
    )
    op.create_table('ttrss_user_prefs',
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('pref_name', sa.String(length=250), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pref_name'], ['ttrss_prefs.pref_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile'], ['ttrss_settings_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_uid', 'pref_name', 'profile')
    )
    op.create_index('ttrss_user_prefs_owner_uid_index', 'ttrss_user_prefs', ['owner_uid'], unique=False)
    op.create_index('ttrss_user_prefs_pref_name_idx', 'ttrss_user_prefs', ['pref_name'], unique=False)
    op.create_table('ttrss_filters2_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('reg_exp', sa.String(length=250), nullable=False),
    sa.Column('inverse', sa.Boolean(), nullable=False),
    sa.Column('filter_type', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('cat_filter', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['ttrss_feed_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['ttrss_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['ttrss_filters2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_type'], ['ttrss_filter_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttrss_user_entries',
    sa.Column('int_id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=200), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('orig_feed_id', sa.Integer(), nullable=True),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('marked', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('tag_cache', sa.Text(), nullable=False),
    sa.Column('label_cache', sa.Text(), nullable=False),
    sa.Column('last_read', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_marked', sa.DateTime(), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['ttrss_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_id'], ['ttrss_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('int_id')
    )
    op.create_index(op.f('ix_ttrss_user_entries_feed_id'), 'ttrss_user_entries', ['feed_id'], unique=False)
    op.create_index(op.f('ix_ttrss_user_entries_owner_uid'), 'ttrss_user_entries', ['owner_uid'], unique=False)
    op.create_index(op.f('ix_ttrss_user_entries_ref_id'), 'ttrss_user_entries', ['ref_id'], unique=False)
    op.create_index(op.f('ix_ttrss_user_entries_unread'), 'ttrss_user_entries', ['unread'], unique=False)
    op.create_table('ttrss_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=250), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('post_int_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['ttrss_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_int_id'], ['ttrss_user_entries.int_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttrss_tags_owner_uid'), 'ttrss_tags', ['owner_uid'], unique=False)
    op.create_index(op.f('ix_ttrss_tags_post_int_id'), 'ttrss_tags', ['post_int_id'], unique=False)
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------
    # Seed data — 75 rows across 6 tables (FK insertion order)
    # Source: ttrss/schema/ttrss_schema_pgsql.sql (INSERT statements)
    # -----------------------------------------------------------------------

    # 1. ttrss_prefs_types (3 rows) — FK parent: ttrss_prefs.type_id
    # Source: ttrss_schema_pgsql.sql lines 282-284
    op.bulk_insert(
        sa.table("ttrss_prefs_types",
                 sa.column("id", sa.Integer),
                 sa.column("type_name", sa.String)),
        [
            {"id": 1, "type_name": "bool"},
            {"id": 2, "type_name": "string"},
            {"id": 3, "type_name": "integer"},
        ],
    )

    # 2. ttrss_prefs_sections (4 rows) — FK parent: ttrss_prefs.section_id
    # Source: ttrss_schema_pgsql.sql lines 290-293
    op.bulk_insert(
        sa.table("ttrss_prefs_sections",
                 sa.column("id", sa.Integer),
                 sa.column("section_name", sa.String),
                 sa.column("order_id", sa.Integer)),
        [
            {"id": 1, "section_name": "General",   "order_id": 0},
            {"id": 2, "section_name": "Interface",  "order_id": 1},
            {"id": 3, "section_name": "Advanced",   "order_id": 3},
            {"id": 4, "section_name": "Digest",     "order_id": 2},
        ],
    )

    # 3. ttrss_filter_types (7 rows) — no FK deps
    # Source: ttrss_schema_pgsql.sql lines 192-198
    op.bulk_insert(
        sa.table("ttrss_filter_types",
                 sa.column("id", sa.Integer),
                 sa.column("name", sa.String),
                 sa.column("description", sa.String)),
        [
            {"id": 1, "name": "title",   "description": "Title"},
            {"id": 2, "name": "content", "description": "Content"},
            {"id": 3, "name": "both",    "description": "Title or Content"},
            {"id": 4, "name": "link",    "description": "Link"},
            {"id": 5, "name": "date",    "description": "Article Date"},
            {"id": 6, "name": "author",  "description": "Author"},
            {"id": 7, "name": "tag",     "description": "Article Tags"},
        ],
    )

    # 4. ttrss_filter_actions (8 rows) — no FK deps
    # Source: ttrss_schema_pgsql.sql lines 208-229
    op.bulk_insert(
        sa.table("ttrss_filter_actions",
                 sa.column("id", sa.Integer),
                 sa.column("name", sa.String),
                 sa.column("description", sa.String)),
        [
            {"id": 1, "name": "filter",  "description": "Delete article"},
            {"id": 2, "name": "catchup", "description": "Mark as read"},
            {"id": 3, "name": "mark",    "description": "Set starred"},
            {"id": 4, "name": "tag",     "description": "Assign tags"},
            {"id": 5, "name": "publish", "description": "Publish article"},
            {"id": 6, "name": "score",   "description": "Modify score"},
            {"id": 7, "name": "label",   "description": "Assign label"},
            {"id": 8, "name": "stop",    "description": "Stop / Do nothing"},
        ],
    )

    # 5. ttrss_prefs (52 rows) — depends on prefs_types + prefs_sections
    # Source: ttrss_schema_pgsql.sql lines 302-352
    # Columns: pref_name (PK varchar), type_id, def_value, section_id
    # access_level defaults to 0; UPDATE below sets 8 prefs to access_level=1
    op.bulk_insert(
        sa.table("ttrss_prefs",
                 sa.column("pref_name", sa.String),
                 sa.column("type_id", sa.Integer),
                 sa.column("def_value", sa.Text),
                 sa.column("section_id", sa.Integer),
                 sa.column("access_level", sa.Integer)),
        [
            {"pref_name": "PURGE_OLD_DAYS",              "type_id": 3, "def_value": "60",           "section_id": 1, "access_level": 0},
            {"pref_name": "DEFAULT_UPDATE_INTERVAL",     "type_id": 3, "def_value": "30",           "section_id": 1, "access_level": 0},
            {"pref_name": "DEFAULT_ARTICLE_LIMIT",       "type_id": 3, "def_value": "30",           "section_id": 2, "access_level": 0},
            {"pref_name": "ALLOW_DUPLICATE_POSTS",       "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "ENABLE_FEED_CATS",            "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 0},
            {"pref_name": "SHOW_CONTENT_PREVIEW",        "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 1},
            {"pref_name": "SHORT_DATE_FORMAT",           "type_id": 2, "def_value": "M d, G:i",     "section_id": 3, "access_level": 0},
            {"pref_name": "LONG_DATE_FORMAT",            "type_id": 2, "def_value": "D, M d Y - G:i", "section_id": 3, "access_level": 0},
            {"pref_name": "COMBINED_DISPLAY_MODE",       "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 0},
            {"pref_name": "HIDE_READ_FEEDS",             "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 0},
            {"pref_name": "ON_CATCHUP_SHOW_NEXT_FEED",   "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 1},
            {"pref_name": "FEEDS_SORT_BY_UNREAD",        "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 0},
            {"pref_name": "REVERSE_HEADLINES",           "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 0},
            {"pref_name": "DIGEST_ENABLE",               "type_id": 1, "def_value": "false",        "section_id": 4, "access_level": 0},
            {"pref_name": "CONFIRM_FEED_CATCHUP",        "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 0},
            {"pref_name": "CDM_AUTO_CATCHUP",            "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 0},
            {"pref_name": "_DEFAULT_VIEW_MODE",          "type_id": 2, "def_value": "adaptive",     "section_id": 1, "access_level": 0},
            {"pref_name": "_DEFAULT_VIEW_LIMIT",         "type_id": 3, "def_value": "30",           "section_id": 1, "access_level": 0},
            {"pref_name": "_PREFS_ACTIVE_TAB",           "type_id": 2, "def_value": "",             "section_id": 1, "access_level": 0},
            {"pref_name": "STRIP_UNSAFE_TAGS",           "type_id": 1, "def_value": "true",         "section_id": 3, "access_level": 0},
            {"pref_name": "BLACKLISTED_TAGS",            "type_id": 2, "def_value": "main, generic, misc, uncategorized, blog, blogroll, general, news", "section_id": 3, "access_level": 0},
            {"pref_name": "FRESH_ARTICLE_MAX_AGE",       "type_id": 3, "def_value": "24",           "section_id": 2, "access_level": 1},
            {"pref_name": "DIGEST_CATCHUP",              "type_id": 1, "def_value": "false",        "section_id": 4, "access_level": 0},
            {"pref_name": "CDM_EXPANDED",                "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 1},
            {"pref_name": "PURGE_UNREAD_ARTICLES",       "type_id": 1, "def_value": "true",         "section_id": 3, "access_level": 0},
            {"pref_name": "HIDE_READ_SHOWS_SPECIAL",     "type_id": 1, "def_value": "true",         "section_id": 2, "access_level": 1},
            {"pref_name": "VFEED_GROUP_BY_FEED",         "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 1},
            {"pref_name": "STRIP_IMAGES",                "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 0},
            {"pref_name": "_DEFAULT_VIEW_ORDER_BY",      "type_id": 2, "def_value": "default",      "section_id": 1, "access_level": 0},
            {"pref_name": "ENABLE_API_ACCESS",           "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_COLLAPSED_SPECIAL",          "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_COLLAPSED_LABELS",           "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_COLLAPSED_UNCAT",            "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_COLLAPSED_FEEDLIST",         "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_MOBILE_ENABLE_CATS",         "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_MOBILE_SHOW_IMAGES",         "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_MOBILE_HIDE_READ",           "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_MOBILE_SORT_FEEDS_UNREAD",   "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_THEME_ID",                   "type_id": 2, "def_value": "0",            "section_id": 1, "access_level": 0},
            {"pref_name": "USER_TIMEZONE",               "type_id": 2, "def_value": "Automatic",    "section_id": 1, "access_level": 0},
            {"pref_name": "USER_STYLESHEET",             "type_id": 2, "def_value": "",             "section_id": 2, "access_level": 0},
            {"pref_name": "SORT_HEADLINES_BY_FEED_DATE", "type_id": 1, "def_value": "false",        "section_id": 2, "access_level": 1},
            {"pref_name": "_MOBILE_BROWSE_CATS",         "type_id": 1, "def_value": "true",         "section_id": 1, "access_level": 0},
            {"pref_name": "SSL_CERT_SERIAL",             "type_id": 2, "def_value": "",             "section_id": 3, "access_level": 0},
            {"pref_name": "DIGEST_PREFERRED_TIME",       "type_id": 2, "def_value": "00:00",        "section_id": 4, "access_level": 0},
            {"pref_name": "_PREFS_SHOW_EMPTY_CATS",      "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "_DEFAULT_INCLUDE_CHILDREN",   "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "AUTO_ASSIGN_LABELS",          "type_id": 1, "def_value": "false",        "section_id": 3, "access_level": 1},
            {"pref_name": "_ENABLED_PLUGINS",            "type_id": 2, "def_value": "",             "section_id": 1, "access_level": 0},
            {"pref_name": "_MOBILE_REVERSE_HEADLINES",   "type_id": 1, "def_value": "false",        "section_id": 1, "access_level": 0},
            {"pref_name": "USER_CSS_THEME",              "type_id": 2, "def_value": "",             "section_id": 2, "access_level": 0},
            {"pref_name": "USER_LANGUAGE",               "type_id": 2, "def_value": "",             "section_id": 2, "access_level": 0},
        ],
    )

    # 6. ttrss_version (1 row) — schema version 124
    # Source: ttrss_schema_pgsql.sql line 264
    op.execute("INSERT INTO ttrss_version (schema_version) VALUES (124)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ttrss_tags_post_int_id'), table_name='ttrss_tags')
    op.drop_index(op.f('ix_ttrss_tags_owner_uid'), table_name='ttrss_tags')
    op.drop_table('ttrss_tags')
    op.drop_index(op.f('ix_ttrss_user_entries_unread'), table_name='ttrss_user_entries')
    op.drop_index(op.f('ix_ttrss_user_entries_ref_id'), table_name='ttrss_user_entries')
    op.drop_index(op.f('ix_ttrss_user_entries_owner_uid'), table_name='ttrss_user_entries')
    op.drop_index(op.f('ix_ttrss_user_entries_feed_id'), table_name='ttrss_user_entries')
    op.drop_table('ttrss_user_entries')
    op.drop_table('ttrss_filters2_rules')
    op.drop_index('ttrss_user_prefs_pref_name_idx', table_name='ttrss_user_prefs')
    op.drop_index('ttrss_user_prefs_owner_uid_index', table_name='ttrss_user_prefs')
    op.drop_table('ttrss_user_prefs')
    op.drop_table('ttrss_user_labels2')
    op.drop_table('ttrss_filters2_actions')
    op.drop_index(op.f('ix_ttrss_feeds_owner_uid'), table_name='ttrss_feeds')
    op.drop_index(op.f('ix_ttrss_feeds_cat_id'), table_name='ttrss_feeds')
    op.drop_table('ttrss_feeds')
    op.drop_table('ttrss_settings_profiles')
    op.drop_index('ttrss_prefs_pref_name_idx', table_name='ttrss_prefs')
    op.drop_table('ttrss_prefs')
    op.drop_table('ttrss_plugin_storage')
    op.drop_table('ttrss_linked_feeds')
    op.drop_table('ttrss_labels2')
    op.drop_table('ttrss_filters2')
    op.drop_table('ttrss_feed_categories')
    op.drop_table('ttrss_error_log')
    op.drop_index('ttrss_entry_comments_ref_id_index', table_name='ttrss_entry_comments')
    op.drop_table('ttrss_entry_comments')
    op.drop_index(op.f('ix_ttrss_enclosures_post_id'), table_name='ttrss_enclosures')
    op.drop_table('ttrss_enclosures')
    op.drop_index('ttrss_counters_cache_value_idx', table_name='ttrss_counters_cache')
    op.drop_index('ttrss_counters_cache_owner_uid_idx', table_name='ttrss_counters_cache')
    op.drop_index('ttrss_counters_cache_feed_id_idx', table_name='ttrss_counters_cache')
    op.drop_table('ttrss_counters_cache')
    op.drop_index('ttrss_cat_counters_cache_owner_uid_idx', table_name='ttrss_cat_counters_cache')
    op.drop_table('ttrss_cat_counters_cache')
    op.drop_table('ttrss_archived_feeds')
    op.drop_table('ttrss_access_keys')
    op.drop_table('ttrss_version')
    op.drop_table('ttrss_users')
    op.drop_index('ttrss_sessions_expire_index', table_name='ttrss_sessions')
    op.drop_table('ttrss_sessions')
    op.drop_table('ttrss_prefs_types')
    op.drop_table('ttrss_prefs_sections')
    op.drop_table('ttrss_linked_instances')
    op.drop_table('ttrss_filter_types')
    op.drop_table('ttrss_filter_actions')
    op.drop_table('ttrss_feedbrowser_cache')
    op.drop_index(op.f('ix_ttrss_entries_updated'), table_name='ttrss_entries')
    op.drop_index(op.f('ix_ttrss_entries_date_entered'), table_name='ttrss_entries')
    op.drop_table('ttrss_entries')
    # ### end Alembic commands ###
